# Generated by Django 4.1.7 on 2024-02-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_image',
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(blank=True, upload_to='category'),
        ),
    ]
